# Generated by Django 6.0.6 on 2026-06-21 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0003_product_supplier_supply_supplyproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='crmApp.storage', verbose_name='Склад'),
        ),
    ]
